#!/bin/sh
set -e

case "$1" in
    remove|deconfigure)
        if [ -d /run/systemd/system ]; then
            deb-systemd-helper disable netevd.service >/dev/null || true
            systemctl --system daemon-reload >/dev/null || true
        fi
        ;;
esac

#DEBHELPER#

exit 0
